// Test factory helpers
export function createMockUser(overrides: Record<string, unknown> = {}) {
  return {
    id: 1,
    telegramId: '123456789',
    username: 'testuser',
    firstName: 'Test',
    lastName: 'User',
    languageCode: 'en',
    language: 'EN' as const,
    isBot: false,
    isBlocked: false,
    coins: 1000,
    totalCoinsEarned: 1000,
    starsBalance: 100,
    level: 1,
    isFishing: false,
    fishingStartedAt: null,
    tankCoins: 0,
    tankCapacity: 100,
    miningRate: 0.0278,
    coinCapacityLevel: 1,
    miningRateLevel: 1,
    lastLoginDate: null,
    loginStreak: 0,
    lastComboDate: null,
    lastComboResult: null,
    referredById: null,
    rewardedLevels: '[]',
    referralEarnings: 0,
    musicEnabled: true,
    lastLoginAt: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    ...overrides,
  };
}
